module.exports = {
    ADD_CHORD: 'ADD_CHORD',
    UPDATE_TRANSPOSITION: 'UPDATE_TRANSPOSITION',
    UPDATE_CAPO: 'UPDATE_CAPO',
    CHANGE_DISPLAY_TYPE: 'CHANGE_DISPLAY_TYPE',
    REMOVE_CHORD: 'REMOVE_CHORD',
    CLEAR_CHORDS: 'CLEAR_CHORDS',
    APPLY_CHORD_PRESET: 'APPLY_CHORD_PRESET'
};
